# Generated by Django 3.2.13 on 2022-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
