# Generated by Django 3.2.13 on 2022-05-08 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_person_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
